"""Rebuild auto-generated AI knowledge base files from source code.

Usage:
    .venv/bin/python docs/ai/rebuild.py [--quiet]

Generates:
    docs/ai/architecture.md
    docs/ai/api-surface.md
    docs/ai/data-model.md
"""

import ast
import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

# Paths relative to project root
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_SRC_DIR = _PROJECT_ROOT / "src"
_AI_DIR = _PROJECT_ROOT / "docs" / "ai"

_HEADER = (
    "<!-- AUTO-GENERATED by docs/ai/rebuild.py — do not edit manually -->\n"
    "<!-- Last rebuilt: {timestamp} -->\n\n"
)


def _get_module_docstring(path: Path) -> str:
    """Extract the first line of a module's docstring, or return empty string."""
    try:
        tree = ast.parse(path.read_text())
    except SyntaxError:
        return ""
    docstring = ast.get_docstring(tree)
    if not docstring:
        return ""
    return docstring.strip().split("\n")[0]


def build_file_tree(src_dir: Path) -> list[tuple[str, str]]:
    """Build a sorted list of (relative_path, one_line_description) for all .py files."""
    entries = []
    for py_file in sorted(src_dir.rglob("*.py")):
        rel = py_file.relative_to(src_dir)
        desc = _get_module_docstring(py_file)
        if desc:
            entries.append((str(rel), desc))
    return entries


def _format_signature(node: ast.FunctionDef) -> str:
    """Format a function's signature from its AST node."""
    parts = []
    args = node.args

    # positional args
    num_defaults = len(args.defaults)
    num_args = len(args.args)
    non_default_count = num_args - num_defaults

    for i, arg in enumerate(args.args):
        name = arg.arg
        annotation = ""
        if arg.annotation:
            annotation = f": {ast.unparse(arg.annotation)}"

        if i >= non_default_count:
            default = args.defaults[i - non_default_count]
            default_str = ast.unparse(default)
            parts.append(f"{name}{annotation} = {default_str}")
        else:
            parts.append(f"{name}{annotation}")

    # return annotation
    ret = ""
    if node.returns:
        ret = f" -> {ast.unparse(node.returns)}"

    return f"{node.name}({', '.join(parts)}){ret}"


def _find_function_in_package(pkg_dir: Path, func_name: str) -> dict | None:
    """Search all .py files in pkg_dir for a function definition and return its info."""
    for py_file in sorted(pkg_dir.rglob("*.py")):
        if py_file.name == "__init__.py":
            continue
        try:
            tree = ast.parse(py_file.read_text())
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == func_name:
                sig = _format_signature(node)
                doc = ast.get_docstring(node) or ""
                return {
                    "name": func_name,
                    "signature": sig,
                    "docstring": doc.strip().split("\n")[0] if doc else "",
                    "source_file": str(py_file.relative_to(pkg_dir.parent)),
                }
            if isinstance(node, ast.ClassDef) and node.name == func_name:
                doc = ast.get_docstring(node) or ""
                return {
                    "name": func_name,
                    "signature": f"class {func_name}",
                    "docstring": doc.strip().split("\n")[0] if doc else "",
                    "source_file": str(py_file.relative_to(pkg_dir.parent)),
                }
    return None


def get_package_exports(pkg_dir: Path) -> list[dict]:
    """Extract exported names from a package's __init__.py and resolve their signatures."""
    init_path = pkg_dir / "__init__.py"
    if not init_path.exists():
        return []

    try:
        tree = ast.parse(init_path.read_text())
    except SyntaxError:
        return []

    # Find __all__ list
    all_names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    if isinstance(node.value, ast.List):
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                all_names.append(elt.value)

    exports = []
    for name in all_names:
        info = _find_function_in_package(pkg_dir, name)
        if info:
            exports.append(info)
        else:
            # It might be a re-exported constant or type — note it without signature
            exports.append({
                "name": name,
                "signature": name,
                "docstring": "",
                "source_file": str(pkg_dir.name / Path("__init__.py")),
            })

    return exports


def extract_routes(server_path: Path) -> list[tuple[str, str]]:
    """Extract HTTP routes from a server.py file.

    Parses the AST looking for do_GET/do_POST/do_PUT methods and their
    self.path comparisons. Returns list of (METHOD, path) tuples.
    """
    try:
        tree = ast.parse(server_path.read_text())
    except SyntaxError:
        return []

    routes = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if not node.name.startswith("do_"):
            continue
        method = node.name[3:]  # "do_GET" -> "GET"

        for child in ast.walk(node):
            # Match: self.path == "/some/path"
            if isinstance(child, ast.Compare):
                if (isinstance(child.left, ast.Attribute)
                        and isinstance(child.left.value, ast.Name)
                        and child.left.value.id == "self"
                        and child.left.attr == "path"):
                    for op, comparator in zip(child.ops, child.comparators):
                        if isinstance(op, ast.Eq) and isinstance(comparator, ast.Constant):
                            routes.append((method, comparator.value))

            # Match: self.path.startswith("/some/prefix")
            if isinstance(child, ast.Call):
                if (isinstance(child.func, ast.Attribute)
                        and child.func.attr == "startswith"
                        and isinstance(child.func.value, ast.Attribute)
                        and isinstance(child.func.value.value, ast.Name)
                        and child.func.value.value.id == "self"
                        and child.func.value.attr == "path"):
                    if child.args and isinstance(child.args[0], ast.Constant):
                        prefix = child.args[0].value
                        routes.append((method, prefix.rstrip("/") + "/:id"))

    return routes


def generate_architecture(src_dir: Path) -> str:
    """Generate the architecture.md content."""
    lines = ["# Architecture\n"]

    # File tree
    lines.append("## File Tree\n")
    lines.append("| File | Description |")
    lines.append("|------|-------------|")
    for rel_path, desc in build_file_tree(src_dir):
        lines.append(f"| `src/{rel_path}` | {desc} |")

    # Package exports summary
    lines.append("\n## Package Exports\n")
    for pkg_dir in sorted(src_dir.iterdir()):
        if not pkg_dir.is_dir() or pkg_dir.name.startswith("_"):
            continue
        init = pkg_dir / "__init__.py"
        if not init.exists():
            continue
        doc = _get_module_docstring(init)
        exports = get_package_exports(pkg_dir)
        export_names = [e["name"] for e in exports]
        if export_names:
            lines.append(f"- **{pkg_dir.name}**: {', '.join(f'`{n}`' for n in export_names)}")
            if doc:
                lines.append(f"  - {doc}")

    # Standalone modules
    lines.append("\n## Standalone Modules\n")
    for py_file in sorted(src_dir.glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        doc = _get_module_docstring(py_file)
        if doc:
            lines.append(f"- **`src/{py_file.name}`**: {doc}")

    # HTTP routes
    server_path = src_dir / "web" / "server.py"
    if server_path.exists():
        routes = extract_routes(server_path)
        if routes:
            lines.append("\n## HTTP API Endpoints\n")
            lines.append("| Method | Path |")
            lines.append("|--------|------|")
            for method, path in routes:
                lines.append(f"| {method} | `{path}` |")

    return "\n".join(lines) + "\n"


def _get_module_functions(py_path: Path) -> list[dict]:
    """Extract all top-level function signatures from a module."""
    try:
        tree = ast.parse(py_path.read_text())
    except SyntaxError:
        return []
    funcs = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            sig = _format_signature(node)
            doc = ast.get_docstring(node) or ""
            funcs.append({
                "name": node.name,
                "signature": sig,
                "docstring": doc.strip().split("\n")[0] if doc else "",
            })
    return funcs


def generate_api_surface(src_dir: Path) -> str:
    """Generate the api-surface.md content."""
    lines = ["# API Surface\n"]

    # Package exports with full signatures
    for pkg_dir in sorted(src_dir.iterdir()):
        if not pkg_dir.is_dir() or pkg_dir.name.startswith("_"):
            continue
        init = pkg_dir / "__init__.py"
        if not init.exists():
            continue
        exports = get_package_exports(pkg_dir)
        if not exports:
            continue
        doc = _get_module_docstring(init)
        lines.append(f"## {pkg_dir.name}\n")
        if doc:
            lines.append(f"{doc}\n")
        for exp in exports:
            lines.append(f"### `{exp['signature']}`\n")
            if exp["docstring"]:
                lines.append(f"{exp['docstring']}\n")
            lines.append(f"*Defined in `{exp['source_file']}`*\n")

    # Standalone modules
    standalone = []
    for py_file in sorted(src_dir.glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        funcs = _get_module_functions(py_file)
        if funcs:
            standalone.append((py_file, funcs))

    if standalone:
        lines.append("## Standalone Modules\n")
        for py_file, funcs in standalone:
            doc = _get_module_docstring(py_file)
            lines.append(f"### `src/{py_file.name}`\n")
            if doc:
                lines.append(f"{doc}\n")
            for f in funcs:
                lines.append(f"#### `{f['signature']}`\n")
                if f["docstring"]:
                    lines.append(f"{f['docstring']}\n")

    return "\n".join(lines) + "\n"


def _extract_schema(schema_path: Path) -> str | None:
    """Extract PERSON_SCHEMA as formatted JSON from schema.py."""
    if not schema_path.exists():
        return None
    try:
        tree = ast.parse(schema_path.read_text())
    except SyntaxError:
        return None
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "PERSON_SCHEMA":
                    # Evaluate the literal safely
                    try:
                        value = ast.literal_eval(node.value)
                        return json.dumps(value, indent=2)
                    except (ValueError, TypeError):
                        return None
    return None


def generate_data_model(src_dir: Path) -> str:
    """Generate the data-model.md content."""
    lines = ["# Data Model\n"]

    # PERSON_SCHEMA
    schema_path = src_dir / "extraction" / "schema.py"
    schema_json = _extract_schema(schema_path)
    if schema_json:
        lines.append("## PERSON_SCHEMA\n")
        lines.append("The canonical structure for extracted memorial card data:\n")
        lines.append("```json")
        lines.append(schema_json)
        lines.append("```\n")

    # Derived fields (computed post-extraction, not in LLM schema)
    lines.append("## Derived Fields\n")
    lines.append(
        "Fields computed post-extraction and persisted in the card JSON, "
        "but not part of the LLM output schema:\n"
    )
    lines.append("| Field | Type | Description |")
    lines.append("|-------|------|-------------|")
    lines.append(
        "| `person.locality` | `string` (non-nullable) | "
        "One of: Haaltert, Kerksken, Denderhoutem, Terjoden, Heldergem. "
        "Derived from `death_place` (preferred) or `birth_place` via "
        "case-insensitive substring matching, defaulting to \"Haaltert\". "
        "Editable in the Review UI. |"
    )

    # Directory layout
    lines.append("\n## Directory Layout\n")
    dirs = [
        ("input/", "Scanned memorial card images (front + back pairs)"),
        ("output/json/", "Per-card JSON files (UUID-keyed, one per confirmed pair)"),
        ("output/text/", "Raw OCR text output (before LLM interpretation)"),
        ("output/export/", "Final stitched images + consolidated memorial_cards.json"),
        ("prompts/", "LLM system/user prompt templates (user-editable)"),
    ]
    lines.append("| Directory | Purpose |")
    lines.append("|-----------|---------|")
    for d, purpose in dirs:
        lines.append(f"| `{d}` | {purpose} |")

    # JSON lifecycle
    lines.append("\n## JSON File Lifecycle\n")
    lines.append(
        "1. **Skeleton** — created at match confirm, contains only "
        "`source.front_image_file` and `source.back_image_file`\n"
        "2. **Enriched** — after LLM extraction, `person` and `notes` fields are added\n"
        "3. **Reviewed** — after human correction in the review UI, fields may be updated\n"
        "4. **Exported** — consolidated into `output/export/memorial_cards.json` with derived filenames\n"
    )

    return "\n".join(lines) + "\n"


def _write_if_changed(path: Path, content: str, quiet: bool) -> bool:
    """Write content to path only if it differs. Returns True if written."""
    timestamped = _HEADER.format(
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    ) + content

    # For comparison, strip the timestamp line (it changes every run)
    def _strip_timestamp(text: str) -> str:
        lines = text.split("\n")
        return "\n".join(l for l in lines if not l.startswith("<!-- Last rebuilt:"))

    if path.exists():
        existing = path.read_text()
        if _strip_timestamp(existing) == _strip_timestamp(timestamped):
            return False

    path.write_text(timestamped)
    if not quiet:
        print(f"Updated {path}")
    return True


def rebuild_all(
    src_dir: Path,
    ai_dir: Path,
    quiet: bool = False,
) -> int:
    """Regenerate all auto-generated knowledge base files.

    Returns the number of files that were updated.
    """
    ai_dir.mkdir(parents=True, exist_ok=True)
    updated = 0

    arch = generate_architecture(src_dir)
    if _write_if_changed(ai_dir / "architecture.md", arch, quiet):
        updated += 1

    api = generate_api_surface(src_dir)
    if _write_if_changed(ai_dir / "api-surface.md", api, quiet):
        updated += 1

    data = generate_data_model(src_dir)
    if _write_if_changed(ai_dir / "data-model.md", data, quiet):
        updated += 1

    if not quiet and updated == 0:
        print("Knowledge base is up to date.")

    return updated


def main():
    parser = argparse.ArgumentParser(description="Rebuild AI knowledge base")
    parser.add_argument("--quiet", action="store_true",
                        help="Suppress output unless files changed")
    args = parser.parse_args()

    rebuild_all(_SRC_DIR, _AI_DIR, quiet=args.quiet)


if __name__ == "__main__":
    main()
