"""Rebuild auto-generated AI knowledge base files from source code.

Usage:
    .venv/bin/python docs/ai/rebuild.py [--quiet]

Generates:
    docs/ai/architecture.md
    docs/ai/api-surface.md
    docs/ai/data-model.md
"""

import ast
import argparse
import json
import re
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

# Paths relative to project root
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_SRC_DIR = _PROJECT_ROOT / "src"
_AI_DIR = _PROJECT_ROOT / "docs" / "ai"

_HEADER = (
    "<!-- AUTO-GENERATED by docs/ai/rebuild.py — do not edit manually -->\n"
    "<!-- Last rebuilt: {timestamp} -->\n\n"
)


def _get_module_docstring(path: Path) -> str:
    """Extract the first line of a module's docstring, or return empty string."""
    try:
        tree = ast.parse(path.read_text())
    except SyntaxError:
        return ""
    docstring = ast.get_docstring(tree)
    if not docstring:
        return ""
    return docstring.strip().split("\n")[0]


def build_file_tree(src_dir: Path) -> list[tuple[str, str]]:
    """Build a sorted list of (relative_path, one_line_description) for all .py files."""
    entries = []
    for py_file in sorted(src_dir.rglob("*.py")):
        rel = py_file.relative_to(src_dir)
        desc = _get_module_docstring(py_file)
        if desc:
            entries.append((str(rel), desc))
    return entries


def _format_signature(node: ast.FunctionDef) -> str:
    """Format a function's signature from its AST node."""
    parts = []
    args = node.args

    # positional args
    num_defaults = len(args.defaults)
    num_args = len(args.args)
    non_default_count = num_args - num_defaults

    for i, arg in enumerate(args.args):
        name = arg.arg
        annotation = ""
        if arg.annotation:
            annotation = f": {ast.unparse(arg.annotation)}"

        if i >= non_default_count:
            default = args.defaults[i - non_default_count]
            default_str = ast.unparse(default)
            parts.append(f"{name}{annotation} = {default_str}")
        else:
            parts.append(f"{name}{annotation}")

    # return annotation
    ret = ""
    if node.returns:
        ret = f" -> {ast.unparse(node.returns)}"

    return f"{node.name}({', '.join(parts)}){ret}"


def _find_function_in_package(pkg_dir: Path, func_name: str) -> dict | None:
    """Search all .py files in pkg_dir for a function definition and return its info."""
    for py_file in sorted(pkg_dir.rglob("*.py")):
        if py_file.name == "__init__.py":
            continue
        try:
            tree = ast.parse(py_file.read_text())
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == func_name:
                sig = _format_signature(node)
                doc = ast.get_docstring(node) or ""
                return {
                    "name": func_name,
                    "signature": sig,
                    "docstring": doc.strip().split("\n")[0] if doc else "",
                    "source_file": str(py_file.relative_to(pkg_dir.parent)),
                }
            if isinstance(node, ast.ClassDef) and node.name == func_name:
                doc = ast.get_docstring(node) or ""
                return {
                    "name": func_name,
                    "signature": f"class {func_name}",
                    "docstring": doc.strip().split("\n")[0] if doc else "",
                    "source_file": str(py_file.relative_to(pkg_dir.parent)),
                }
    return None


def get_package_exports(pkg_dir: Path) -> list[dict]:
    """Extract exported names from a package's __init__.py and resolve their signatures."""
    init_path = pkg_dir / "__init__.py"
    if not init_path.exists():
        return []

    try:
        tree = ast.parse(init_path.read_text())
    except SyntaxError:
        return []

    # Find __all__ list
    all_names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "__all__":
                    if isinstance(node.value, ast.List):
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                all_names.append(elt.value)

    exports = []
    for name in all_names:
        info = _find_function_in_package(pkg_dir, name)
        if info:
            exports.append(info)
        else:
            # It might be a re-exported constant or type — note it without signature
            exports.append({
                "name": name,
                "signature": name,
                "docstring": "",
                "source_file": str(pkg_dir.name / Path("__init__.py")),
            })

    return exports


def extract_routes(server_path: Path) -> list[tuple[str, str]]:
    """Extract HTTP routes from a server.py file.

    Parses the AST looking for do_GET/do_POST/do_PUT methods and their
    self.path comparisons. Returns list of (METHOD, path) tuples.
    """
    try:
        tree = ast.parse(server_path.read_text())
    except SyntaxError:
        return []

    routes = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if not node.name.startswith("do_"):
            continue
        method = node.name[3:]  # "do_GET" -> "GET"

        for child in ast.walk(node):
            # Match: self.path == "/some/path"
            if isinstance(child, ast.Compare):
                if (isinstance(child.left, ast.Attribute)
                        and isinstance(child.left.value, ast.Name)
                        and child.left.value.id == "self"
                        and child.left.attr == "path"):
                    for op, comparator in zip(child.ops, child.comparators):
                        if isinstance(op, ast.Eq) and isinstance(comparator, ast.Constant):
                            routes.append((method, comparator.value))

            # Match: self.path.startswith("/some/prefix")
            if isinstance(child, ast.Call):
                if (isinstance(child.func, ast.Attribute)
                        and child.func.attr == "startswith"
                        and isinstance(child.func.value, ast.Attribute)
                        and isinstance(child.func.value.value, ast.Name)
                        and child.func.value.value.id == "self"
                        and child.func.value.attr == "path"):
                    if child.args and isinstance(child.args[0], ast.Constant):
                        prefix = child.args[0].value
                        routes.append((method, prefix.rstrip("/") + "/:id"))

    return routes


def generate_architecture(src_dir: Path) -> str:
    """Generate the architecture.md content."""
    lines = ["# Architecture\n"]

    # File tree
    lines.append("## File Tree\n")
    lines.append("| File | Description |")
    lines.append("|------|-------------|")
    for rel_path, desc in build_file_tree(src_dir):
        lines.append(f"| `src/{rel_path}` | {desc} |")

    # Package exports summary
    lines.append("\n## Package Exports\n")
    for pkg_dir in sorted(src_dir.iterdir()):
        if not pkg_dir.is_dir() or pkg_dir.name.startswith("_"):
            continue
        init = pkg_dir / "__init__.py"
        if not init.exists():
            continue
        doc = _get_module_docstring(init)
        exports = get_package_exports(pkg_dir)
        export_names = [e["name"] for e in exports]
        if export_names:
            lines.append(f"- **{pkg_dir.name}**: {', '.join(f'`{n}`' for n in export_names)}")
            if doc:
                lines.append(f"  - {doc}")

    # Standalone modules
    lines.append("\n## Standalone Modules\n")
    for py_file in sorted(src_dir.glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        doc = _get_module_docstring(py_file)
        if doc:
            lines.append(f"- **`src/{py_file.name}`**: {doc}")

    # HTTP routes
    server_path = src_dir / "web" / "server.py"
    if server_path.exists():
        routes = extract_routes(server_path)
        if routes:
            lines.append("\n## HTTP API Endpoints\n")
            lines.append("| Method | Path |")
            lines.append("|--------|------|")
            for method, path in routes:
                lines.append(f"| {method} | `{path}` |")

    return "\n".join(lines) + "\n"
